# Generated by Django 5.0.4 on 2024-04-19 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papertradingapp', '0005_rename_aapl_yfinancedata_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yfinancedata',
            name='data',
        ),
        migrations.AddField(
            model_name='yfinancedata',
            name='aapl',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='yfinancedata',
            name='amd',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='yfinancedata',
            name='ibm',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='yfinancedata',
            name='intc',
            field=models.JSONField(default=dict),
        ),
    ]
