# Generated by Django 5.0.4 on 2024-04-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papertradingapp', '0006_remove_yfinancedata_data_yfinancedata_aapl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_ticker',
            field=models.CharField(default='null', max_length=5),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='stock',
            name='user_balance',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=9),
        ),
    ]
