# Generated by Django 5.0.4 on 2024-04-19 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papertradingapp', '0009_rename_blanac_userbalance_blance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='stock_value',
            new_name='bought_at',
        ),
    ]
