# Generated by Django 5.0.4 on 2024-04-19 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papertradingapp', '0011_rename_blance_userbalance_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='buy',
        ),
    ]
