# Generated by Django 5.0.4 on 2024-04-21 01:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papertradingapp', '0015_alter_transactionhistory_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='transaction_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 20, 20, 21, 2, 225573)),
        ),
    ]
