# Generated by Django 5.0.4 on 2024-04-16 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papertradingapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbalance',
            old_name='actions',
            new_name='owned',
        ),
    ]
