# Generated by Django 5.0.4 on 2024-04-17 14:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papertradingapp', '0002_rename_actions_userbalance_owned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbalance',
            name='owned',
        ),
        migrations.AddField(
            model_name='userbalance',
            name='portfolio',
            field=models.ManyToManyField(to='papertradingapp.Portfolio'),
            preserve_default=False,
        ),
    ]
