# Generated by Django 5.0.4 on 2024-04-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papertradingapp', '0002_yfinancedata_alter_stock_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='yfinancedata',
            name='aapl',
            field=models.JSONField(default=('Open', 'High', 'Low', 'Close', 'Volume', 'Dividends', 'Stock Splits')),
        ),
        migrations.AddField(
            model_name='yfinancedata',
            name='amd',
            field=models.JSONField(default=('Open', 'High', 'Low', 'Close', 'Volume', 'Dividends', 'Stock Splits')),
        ),
        migrations.AddField(
            model_name='yfinancedata',
            name='imb',
            field=models.JSONField(default=('Open', 'High', 'Low', 'Close', 'Volume', 'Dividends', 'Stock Splits')),
        ),
        migrations.AddField(
            model_name='yfinancedata',
            name='intc',
            field=models.JSONField(default=('Open', 'High', 'Low', 'Close', 'Volume', 'Dividends', 'Stock Splits')),
        ),
    ]
