# Generated by Django 5.0.4 on 2024-04-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papertradingapp', '0003_remove_userbalance_owned_userbalance_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbalance',
            name='portfolio',
        ),
        migrations.AddField(
            model_name='userbalance',
            name='portfolio',
            field=models.ManyToManyField(to='papertradingapp.portfolio'),
        ),
    ]
