# Generated by Django 5.0.4 on 2024-04-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papertradingapp', '0003_yfinancedata_aapl_yfinancedata_amd_yfinancedata_imb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yfinancedata',
            name='aapl',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='yfinancedata',
            name='amd',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='yfinancedata',
            name='imb',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='yfinancedata',
            name='intc',
            field=models.JSONField(),
        ),
    ]
