# Generated by Django 5.0.4 on 2024-04-18 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papertradingapp', '0004_alter_yfinancedata_aapl_alter_yfinancedata_amd_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yfinancedata',
            old_name='aapl',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='yfinancedata',
            name='amd',
        ),
        migrations.RemoveField(
            model_name='yfinancedata',
            name='imb',
        ),
        migrations.RemoveField(
            model_name='yfinancedata',
            name='intc',
        ),
    ]
