# Generated by Django 5.0.4 on 2024-04-17 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papertradingapp', '0004_remove_userbalance_portfolio_userbalance_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbalance',
            name='portfolio',
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_ticker', models.CharField(max_length=4)),
                ('quantity', models.IntegerField(default=0)),
                ('stock_value', models.DecimalField(decimal_places=2, max_digits=9)),
                ('buy', models.BooleanField(default=False)),
                ('user_balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papertradingapp.userbalance')),
            ],
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
