# Generated by Django 5.0.4 on 2024-04-19 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papertradingapp', '0008_remove_stock_user_balance_userbalance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbalance',
            old_name='blanac',
            new_name='blance',
        ),
    ]
