# Generated by Django 5.0.4 on 2024-04-21 01:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papertradingapp', '0014_alter_transactionhistory_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='transaction_date',
            field=models.IntegerField(default=datetime.datetime(2024, 4, 20, 20, 17, 5, 976071)),
        ),
    ]
