# Generated by Django 5.0.4 on 2024-04-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papertradingapp', '0017_alter_transactionhistory_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=9),
        ),
    ]
